POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 03",
    "description": "This is the third video",
    "duration": 300
}

###

GET http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/8418575a-b45d-44bd-9ec4-7704d0a4064e	
Content-Type: application/json

{
    "title": "Video 02",
    "description": "This is the second video",
    "duration": 240
}

###

DELETE http://localhost:3333/videos/ab107955-08b5-49af-9ec1-5761ed974066
